#!/usr/bin/python3

import os 
import subprocess 

var = ['precipitation_amount','tasmax','tasmin']
#fun = ['sum','mean','mean']

for y in var:
  if y == 'precipitation_amount':
    name_var = 'pr'
    fun = 'sum'
  else:
    name_var = y
    fun = 'mean'
  f=open("dataprocess-UW-hist-%s.sh" % (name_var),'w')
  f.write("""#!/bin/bash
#-------------------------------------------------------------------------------
# SBATCH CONFIG
#-------------------------------------------------------------------------------
## resources
#SBATCH --partition Lewis
#SBATCH --nodes=1
#SBATCH --ntasks=1 # leave at '1' unless using a MPI code
#SBATCH --cpus-per-task=8 # cores per task
#SBATCH --mem-per-cpu=8G # memory per core (default is 1GB/core)
#SBATCH --time 0-04:00 # days-hours:minutes
#SBATCH --qos=normal
#SBATCH --account=general # investors will replace this with their account name

## labels and outputs
#SBATCH --job-name=SPEC1-UW

## notifications
#SBATCH --mail-user=htnb4d@mail.missouri.edu # email address for notifications
#SBATCH --mail-type=END,FAIL # which type of notifications to send
#-------------------------------------------------------------------------------

echo "### Starting at: $(date) ###"

# load modules then list loaded modules
module load netcdf/netcdf-4.6.1-openmpi-3.1.3-hdf5-fortran
export HDF5_USE_FILE_LOCKING=FALSE
module load R/R-3.3.3/
module list

# Running script     
Rscript Clim_UW_hist_SPEC1_cluster.R %s %s 
echo "### Ended at: $(date) ###"
    """ % (y, fun) )
  f.close() 
  #os.system("sbatch ismclimprocess-UW-hist-%s.sh" % (name_var))

